Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/mixed_fraction_spec.rb